CREATE TABLE IF NOT EXISTS vai_tro (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ma VARCHAR(50) NOT NULL UNIQUE,
  ten VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tai_khoan (
  id INT AUTO_INCREMENT PRIMARY KEY,
  vai_tro_id INT NOT NULL,
  ho_ten VARCHAR(120) NOT NULL,
  email VARCHAR(120) NOT NULL UNIQUE,
  so_dien_thoai VARCHAR(30) NULL,
  mat_khau VARCHAR(255) NOT NULL,
  trang_thai TINYINT(1) NOT NULL DEFAULT 1,
  tao_luc TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ngay_cap_nhat DATETIME NULL,
  cap_nhat_luc TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_tai_khoan_vai_tro FOREIGN KEY (vai_tro_id) REFERENCES vai_tro(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
