CREATE TABLE IF NOT EXISTS giao_dien (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ma VARCHAR(100) NOT NULL UNIQUE,
    ten VARCHAR(150) NOT NULL,
    mo_dun_ma VARCHAR(100) NOT NULL,
    phien_ban VARCHAR(50) NULL,
    dang_kich_hoat TINYINT DEFAULT 0,
    la_mac_dinh TINYINT DEFAULT 0,
    ngay_tao DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
